pipeline {
    agent {
        docker {
            image 'docker:20.10.12-dind'
            args '-u root'
        }
    }
    stages {
        stage('Setup') {
            steps {
                script {
                    // Usamos 'apk' en lugar de 'apt-get' para Alpine
                    sh 'apk update && apk add python3 py3-pip'
                }
            }
        }
        stage('Build') {
            steps {
                dir('/var/jenkins_home/workspace/prueba3@2') {
                    sh '''
                    echo "Working directory: $(pwd)"
                    ls -la
                    python3 -m py_compile sources/add2vals.py sources/calc.py
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                sh 'pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }

        stage('Deliver') { 
            steps {
                sh "pyinstaller --onefile sources/add2vals.py"
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}
