pipeline {
    agent any

    environment {
        VENV_DIR = './venv'  // Definir el directorio para el entorno virtual
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup') {
            steps {
                script {
                    // Crear un entorno virtual y activar
                    sh 'python3 -m venv $VENV_DIR'
                    sh 'source $VENV_DIR/bin/activate && pip install --upgrade pip'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    // Instalar pytest en el entorno virtual
                    sh 'source $VENV_DIR/bin/activate && pip install pytest'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Ejecutar pruebas
                    sh 'source $VENV_DIR/bin/activate && python -m pytest --junit-xml test-reports/results.xml sources/test_calc.py'
                }
            }
        }

        stage('Archive Test Results') {
            steps {
                junit 'test-reports/results.xml'
            }
        }
    }

    post {
        always {
            // Limpiar entorno
            sh 'rm -rf $VENV_DIR'
        }
    }
}
